using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class AvatarAttributesModel
{
    [RealtimeProperty(1, true, true)] private string _nickname;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class AvatarAttributesModel : RealtimeModel {
    public string nickname {
        get {
            return _nicknameProperty.value;
        }
        set {
            if (_nicknameProperty.value == value) return;
            _nicknameProperty.value = value;
            InvalidateReliableLength();
            FireNicknameDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(AvatarAttributesModel model, T value);
    public event PropertyChangedHandler<string> nicknameDidChange;
    
    public enum PropertyID : uint {
        Nickname = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _nicknameProperty;
    
    #endregion
    
    public AvatarAttributesModel() : base(null) {
        _nicknameProperty = new ReliableProperty<string>(1, _nickname);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _nicknameProperty.UnsubscribeCallback();
    }
    
    private void FireNicknameDidChange(string value) {
        try {
            nicknameDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _nicknameProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _nicknameProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Nickname: {
                    changed = _nicknameProperty.Read(stream, context);
                    if (changed) FireNicknameDidChange(nickname);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _nickname = nickname;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
