using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]
public partial class AvatarSoundModel
{
    [RealtimeProperty(1, true, true)] private bool _playSoud;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class AvatarSoundModel : RealtimeModel {
    public bool playSoud {
        get {
            return _playSoudProperty.value;
        }
        set {
            if (_playSoudProperty.value == value) return;
            _playSoudProperty.value = value;
            InvalidateReliableLength();
            FirePlaySoudDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(AvatarSoundModel model, T value);
    public event PropertyChangedHandler<bool> playSoudDidChange;
    
    public enum PropertyID : uint {
        PlaySoud = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _playSoudProperty;
    
    #endregion
    
    public AvatarSoundModel() : base(null) {
        _playSoudProperty = new ReliableProperty<bool>(1, _playSoud);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _playSoudProperty.UnsubscribeCallback();
    }
    
    private void FirePlaySoudDidChange(bool value) {
        try {
            playSoudDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _playSoudProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _playSoudProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.PlaySoud: {
                    changed = _playSoudProperty.Read(stream, context);
                    if (changed) FirePlaySoudDidChange(playSoud);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _playSoud = playSoud;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
